/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.gui;

import com.sun.awt.AWTUtilities;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.geom.RoundRectangle2D;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.StringTokenizer;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import ufps.negocio.ErrorHTML;
import ufps.util.Pila;

/**
 *
 * @author hogar
 */
public class CrearArchivo extends javax.swing.JFrame {

    private Principal myP;
    private int x;
    private int y;
    String etq="";

    public Principal getMyP() {
        return myP;
    }
   

    /**
     * Creates new form CrearArchivo
     */
    public CrearArchivo(Principal myP) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.myP = myP;
        String cad=this.myP.getM().cargarTags();
        this.cargarCombo(this.comboTipoEtq,cad.split("-"));
        this.etq = this.myP.getM().cargarEtiquetas();
        this.generarTagsEstruturas();
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);

    }
    
    public CrearArchivo(String codigo, Principal myP) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.myP = myP;
        String cad=this.myP.getM().cargarTags();
        this.cargarCombo(this.comboTipoEtq,cad.split("-"));
        this.etq = this.myP.getM().cargarEtiquetas();
        //this.generarTagsEstruturas();
        this.mostrarCodigo(codigo);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);

    }

    private void generarTagsEstruturas() {
        this.areaEscrituraHTML.setText("<!DOCTYPE html>" + "\n" + "\n" + "<html>" + "\n" + "\n" + "<head>" + "\n"
                + "\t" + "<title>" + "esto es un ejemplo " + "</title>" + "\n" + "\n" + "</head>" + "\n" + "\n" + "<body>"
                + "\n" + "\n" + "</body>" + "\n" + "\n" + "</html>");
    }

    private void cargarCombo(JComboBox j, String[] cad) {
     j.removeAllItems();
     j.addItem("seleccione etiqueta ");  
     for (String e : cad) {
      if (!e.isEmpty())
            j.addItem(e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaEscrituraHTML = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        comboTipoEtq = new javax.swing.JComboBox();
        comboEtiquetas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaEscrituraHTML.setColumns(20);
        areaEscrituraHTML.setRows(5);
        jScrollPane1.setViewportView(areaEscrituraHTML);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 360, 400));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("EDITOR DE HTML ");
        jLabel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        jLabel12.setToolTipText("cerrar");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(217, 217, 217)
                .addComponent(jLabel12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3))
                .addGap(83, 83, 83))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 30));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setText("VISTA DE HTML ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VISTA.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 250, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", 0, 0, new java.awt.Font("Arial Black", 1, 18))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel8.setText("TIPO DE TAGS :");

        comboTipoEtq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoEtqActionPerformed(evt);
            }
        });

        comboEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEtiquetasActionPerformed(evt);
            }
        });

        jLabel2.setText("ETIQUETAS :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboTipoEtq, 0, 135, Short.MAX_VALUE)
                    .addComponent(comboEtiquetas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboTipoEtq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("ETIQUETAS HTML");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jButton1.setText("VALIDAR Y GUARDAR ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingeneria de sistemas.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Help-icon.png"))); // NOI18N
        jButton2.setToolTipText("dar click aca para ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point ubicacion = MouseInfo.getPointerInfo().getLocation();//1
        setLocation(ubicacion.x - x, ubicacion.y - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.myP.setVisible(true);
        this.dispose();
     
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       this.leerLineaPorLineaJText();
       this.myP.getM().buscarErrores();
       if(this.myP.getM().hayErrrores()){
        InformeErrores obj=new InformeErrores(this);
        obj.setVisible(true);
        
        }
       else{
           JOptionPane.showMessageDialog(null,"CODIGO EN ORDEN");
          JFileChooser fc = new JFileChooser(); fc.setFileFilter(new
         FileNameExtensionFilter("ArchivoHTML","html"));
          int respuesta =fc.showSaveDialog(this); 
          if (respuesta ==JFileChooser.APPROVE_OPTION) { 
             
        try{
            
            File archivoElegido =fc.getSelectedFile();
            File archivoNuevo=new File(archivoElegido.getPath()+".html");
            archivoNuevo.createNewFile();
            this.leerLineaPorLineaJTextPasarHTML(archivoNuevo);
            JOptionPane.showMessageDialog(null,"SE HA GUARDADO CORRECTAMENTE EL ARCHIVO");
           
           
       }catch(Exception e){ 
           
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed
       }
    }
    private void comboTipoEtqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoEtqActionPerformed
             if(this.comboTipoEtq.getSelectedIndex()==1){
               this.cargarCombo(this.comboEtiquetas,etq.split(",")[0].split(";"));
             }
                  if(this.comboTipoEtq.getSelectedIndex()==2){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[1].split(";"));
         }
                 if(this.comboTipoEtq.getSelectedIndex()==3){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[2].split(";"));
         }
          if(this.comboTipoEtq.getSelectedIndex()==4){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[3].split(";"));
         }   
         if(this.comboTipoEtq.getSelectedIndex()==5){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[4].split(";"));
         }
           if(this.comboTipoEtq.getSelectedIndex()==6){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[5].split(";"));
         }
             if(this.comboTipoEtq.getSelectedIndex()==7){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[6].split(";"));
         }
             if(this.comboTipoEtq.getSelectedIndex()==8){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[7].split(";"));
         }
               if(this.comboTipoEtq.getSelectedIndex()==9){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[8].split(";"));
         }
                if(this.comboTipoEtq.getSelectedIndex()==10){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[9].split(";"));
         }
                 if(this.comboTipoEtq.getSelectedIndex()==11){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[10].split(";"));
         }
                 if(this.comboTipoEtq.getSelectedIndex()==12){
                  this.cargarCombo(this.comboEtiquetas,etq.split(",")[11].split(";"));
         }
  
    }//GEN-LAST:event_comboTipoEtqActionPerformed

    private void comboEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEtiquetasActionPerformed
            if(this.comboEtiquetas.getSelectedIndex()==0){
                           return; 
                       }
                     if(this.comboEtiquetas.getItemCount()>0)
        this.areaEscrituraHTML.insert(this.seleccionEtiquetas(this.comboEtiquetas.getSelectedItem().toString()), this.areaEscrituraHTML.getCaretPosition());
                                   
    }//GEN-LAST:event_comboEtiquetasActionPerformed

    private void jLabel3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel3AncestorAdded
     
    }//GEN-LAST:event_jLabel3AncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Ayuda obj=new Ayuda(this);
      obj.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void leerLineaPorLineaJTextPasarHTML(File archivoHTML){
        try{
    String contenidoT = new String(this.areaEscrituraHTML.getText());
        StringTokenizer st = new StringTokenizer(contenidoT + "\n");
        String cad = "";
        while (st.hasMoreTokens()) {
           this.tomarDatosTextArea(st.nextToken(), archivoHTML,true);
        }
        }catch(Exception e){
        }
    
    }
    
    private void leerLineaPorLineaJText() {
        String contenidoT = new String(this.areaEscrituraHTML.getText());
        StringTokenizer st = new StringTokenizer(contenidoT + "\n");
        String cad = "";
        while (st.hasMoreTokens()) {
            this.myP.getM().tomarCodigoHtml(st.nextToken());
        }
    }

    private void tomarDatosTextArea(String contenido, File archivo, boolean p) throws Exception {
        FileWriter fstream;
        BufferedWriter out;
        fstream = new FileWriter(archivo, true);
        out = new BufferedWriter(fstream);
        out.newLine();
        out.write(contenido);
        out.close();

    }

    private boolean revisarExistenciaSimbolos(String cad) {
        for (int i = 0; i < cad.length(); i++) {
            if (cad.charAt(i) == '<' || cad.charAt(i) == '>') {
                return true;
            }
        }
        return false;
    }

    private String seleccionEtiquetasForm(String cad) {
    
            return cad + "</" + cad.substring(1, cad.length() - 1) + ">";
        
    }

    private String seleccionEtiquetasFormating(String cad) {
        return cad + "</" + cad.substring(1, cad.length() - 1) + ">";
    }

    private String seleccionEtiquetas(String cad) {
        if (cad.equals("<!--...-->")) {
            return cad;
        }
        if (cad.equals("<input>")) {
            return "<" + cad.substring(1, cad.length() - 1) + "/>";
        }
        
        if(cad.equals("<!DOCTYPE> ")){
            return "<"+cad.substring(1,cad.length()-2)+" html>";
        }
        if (cad.equals("<br>") || cad.equals("<hr>")) {
            return "<" + cad.substring(1, cad.length() - 1) + "/>";
        }
        if (cad.equals("< html >")) {
            return "<html>" + "</" + "<html>".substring(1, "<html>".length() - 1) + ">";
        } else {
            return cad + "</" + cad.substring(1, cad.length() - 1) + ">";
        }
    }
    
  
    
  
   

    private String sacarEtiquetaSinEspacios(char[] cad) {
        String res = "";
        for (char c : cad) {
            String carac = String.valueOf(c);
            if (!carac.isEmpty()) {
                res += carac;
            }
        }
        return res;
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaEscrituraHTML;
    private javax.swing.JComboBox comboEtiquetas;
    private javax.swing.JComboBox comboTipoEtq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void mostrarCodigo(String codigo) {
        this.areaEscrituraHTML.setLineWrap(true);
        this.areaEscrituraHTML.setText(codigo);
        //this.areaEscrituraHTML.setLineWrap(false);
    }
}
